# vim:ft=ansible:
---

- name: Create the PKI directory
  shell: ./easyrsa init-pki
    chdir=/etc/openvpn/easy-rsa
    creates=/etc/openvpn/easy-rsa/pki

- name: generate the master Certificate Authority (CA) certificate
  shell: ./easyrsa --batch build-ca nopass
    chdir=/etc/openvpn/easy-rsa/
    creates=/etc/openvpn/easy-rsa/pki/ca.crt
  notify: Backup openvpn certificates

- name: Diffie Hellman parameters must be generated for the OpenVPN server
  shell: ./easyrsa gen-dh
    chdir=/etc/openvpn/easy-rsa/
    creates=/etc/openvpn/easy-rsa/pki/dh.pem
  notify: Backup openvpn certificates

- name: generate the server certificate and key
  shell: ./easyrsa --batch build-server-full server nopass
    chdir=/etc/openvpn/easy-rsa/
    creates=/etc/openvpn/easy-rsa/pki/private/server.key
  notify: Backup openvpn certificates

- name: create revoketion certificate crl.pem
  shell: ./easyrsa gen-crl
    chdir=/etc/openvpn/easy-rsa
    creates=/etc/openvpn/easy-rsa/pki/crl.pem
  notify: Backup openvpn certificates

- name: set file ownerships
  shell: chown -R {{ openvpn_daemon_user }}.{{ openvpn_daemon_group }} /etc/openvpn/easy-rsa
